-- بنك الأفكار - مخطط قاعدة البيانات لـ Supabase
-- شغّل هذا الملف مرة واحدة من: Supabase > SQL Editor

create table if not exists public.employee_registrations (
  id bigint generated by default as identity primary key,
  identity_key text not null unique,
  employee_name text,
  employee_code text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create table if not exists public.ideas (
  id bigint generated by default as identity primary key,
  employee_name text,
  employee_code text,
  category text,
  title text,
  challenge text,
  solution text,
  expected_impact text,
  status text not null default 'جديدة' check (status in ('جديدة','قيد التقييم','معتمدة','قيد التنفيذ','منفذة','مرفوضة')),
  feasibility integer check (feasibility between 1 and 5),
  ease integer check (ease between 1 and 5),
  roi integer check (roi between 1 and 5),
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

create index if not exists ideas_employee_code_idx on public.ideas (employee_code);
create index if not exists ideas_employee_name_idx on public.ideas (employee_name);
create index if not exists registrations_status_idx on public.employee_registrations (status);

-- لا يحتاج المتصفح صلاحية مباشرة على الجداول؛ الاتصال يتم من السيرفر بمفتاح Service Role.
alter table public.employee_registrations enable row level security;
alter table public.ideas enable row level security;

-- صلاحيات الخادم. المفتاح السري في Supabase يعمل بصلاحيات service_role.
grant usage on schema public to service_role;
grant all on table public.employee_registrations to service_role;
grant all on table public.ideas to service_role;
grant usage, select on all sequences in schema public to service_role;
